### ISSUE TITLE
http://dot-bit.org/ returns 404

### ISSUE THREAD

**Issue by obsy** [ericpaulbishop/gargoyle#476]
NameCoin defined as link http://dot-bit.org/ in basic.sh returns 404. Should be removed? Or it was replaced by https://bit.namecoin.info/

**Comment by ericpaulbishop** [comment]
Fixed the link in 27487790f64

I'd REALLY like to find a way that doesn't eat up too many resources that would dynamically load namecoin names and resolve them that way, rather than hardcode namecoin servers but I haven't found a good way of doing this.

My personal opinion is that namecoin is in many ways more important than bitcoin because it allows for a truly secure, distributed way of doing DNS without a central authority. Still, not too many people paying attention to it.
