### ISSUE TITLE
Use SHA256 for HTTPS certificate

### ISSUE THREAD

**Issue by thiagokokada** [ericpaulbishop/gargoyle#531]
Don't know if this is viable without increasing image size, however [Chrome](https://security.googleblog.com/2014/09/gradually-sunsetting-sha-1.html) and other browsers deprecated SHA1 certificates for quite some time, that Gargoyle Firmware still uses by default. While fixing this issue will not remove the red security warns in the browser (since the certificate is self-signed anyway), for those people who really cares about security this would make things easier (so you don't need to re-issue a correct certificate, for example, just include the certificate generated by Gargoyle in Root Certificate Authority).

Btw, the [Gargoyle Website](https://www.gargoyle-router.com/) itself needs a new certificate too.

**Comment by stopspazzing** [comment]
Regarding your last comment: https://www.gargoyle-router.com/phpbb/viewtopic.php?f=5&t=8667

Everything else is sound and good idea.

**Comment by m45t3r** [comment]
Seems to be as simple as creating new `gargoyle/package/gargoyle/files/etc/uhttpd.crt` and `gargoyle/package/gargoyle/files/etc/uhttpd.key` files. Something like this should be enough:

     openssl req -x509 -sha256 -newkey rsa:2048 -keyout certificate.key -out certificate.crt -days 7300 -nodes -subj "/C=US/ST=Some-State/O=Gargoyle Router Management Utility/CN=gargoyle-router.com"

This will create a certificate similar to the one used nowadays, only using SHA256 instead of SHA1, of course.

However, it would be more interesting to maybe generate this certificate during build. Or maybe not, since it seems that #448 already take care of this if you have a router with enough Flash to include OpenSSL.

**Comment by m45t3r** [comment]
Just another think, since you can access Gargoyle from https://gagoyle.lan (just discovered this in OpenWRT Wiki, btw), maybe it would be interesting to change the command above to:

     openssl req -x509 -sha256 -newkey rsa:2048 -keyout certificate.key -out certificate.crt -days 7300 -nodes -subj "/C=US/ST=Some-State/O=Gargoyle Router Management Utility/CN=gargoyle.lan"

This would make access from the above URL "valid" (the user still has to import the Gargoyle certificate into Root Certificate Authority, though).

**Comment by lantis1008** [comment]
The gargoyle.lan designation can be changed by the user as a setting so this may not work for all use cases.

**Comment by m45t3r** [comment]
@lantis1008, yeah, I know, however even if you change the hostname it seems that Gargoyle still maintain the older hostnames active. At least this is my case:

    127.0.0.1 localhost
    192.168.1.1    Gargoyle
    192.168.1.1    MyNewShinyHostname

Btw, I changed the hostname using System->Identification->Hostname.

One alternative would be to use the code from #448 to generate a new certificate if the user changes the hostname, however this may have bigger implications.

**Comment by nworbnhoj** [comment]
since #448 the https certificate is generated on first demand with:
`openssl genpkey -algorithm RSA -out /etc/uhttpd.key -pkeyopt rsa_keygen_bits:2048`
`openssl req -new -key /etc/uhttpd.key -out /etc/uhttpd.csr -subj '/O=gargoyle-router.com/CN=Gargoyle Router Management Utility'`
`openssl x509 -req -days 3650 -in /etc/uhttpd.csr -signkey /etc/uhttpd.key -out /etc/uhttpd.crt`

When I connect to Gargoyle with https I get a certificate with a SHA-256 Fingerprint.

@m45t3r do you see something different?

**Comment by m45t3r** [comment]
@nworbnhoj  Since I build a firmware for routers with 4MB of Flash, there is no OpenSSL installed so the HTTPS certificates used by my routers is the default one included in this repository. And those default certificates still use SHA1.

**Comment by m45t3r** [comment]
Just an idea, px5g is already used by OpenWRT to generate HTTPS certificates instead of OpenSSL (according to them, thanks to the small size of it). Maybe this could be integrated in Gargoyle builds?

However, since there is already a problem with size in routers with 4MB of Flash, maybe not.

**Comment by nworbnhoj** [comment]
@m45t3r Ahhh OK 4M routers - sorry missed that.

Generating the SHA-256 certificate at build would be better for a very few people who build their own image - but (I suspect) the vast majority of users download and install an image from the website.

It should be relatively straight-forward to regenerate the certificate when the user changes the host name as @lantis1008 suggests (assuming OpenSSL is included in the build)

**Comment by m45t3r** [comment]
After thinking a little more about this problem, having a "public private key" seems like a bad idea anyway. It is simple too easy to do a MITM attack. There are some alternatives:
- Only allow user to enable remote HTTPS access if the user changed the default certificate (for local network access this shouldn't be too much of a problem, unless LAN is untrusted too). Include instructions of how to generate a self-signed certificate and how to change it in Wiki. Put a WARN in the default certificate files saying they are insecure and should be changed, including the link for the wiki on how to do it. This can be added to all profiles with almost no increase in size. 
- Include px5g in default image and generate certificates on first boot, like a OpenWRT. A better choice, and maybe there will still be sufficient space for 4MB routers, however I am not sure. 
- Drop 4MB support and simple include OpenSSL in all targets.

**Comment by lantis1008** [comment]
Let's just go custom Diffie-Hellman :P
