### ISSUE TITLE
ddns_provider.conf - update for freedns.afraid.org

### ISSUE THREAD

**Issue by luki92** [ericpaulbishop/gargoyle#555]
Entry for freedns.afraid.org could be replaced with:

```
service freedns.afraid.org
        url_template                    https://freedns.afraid.org/dynamic/update.php?[[KEY]]
        required_variables              domain key
        required_variable_names         DyDNS.DoNm,DyDNS.AKey
        success_regexp                  /(^Updated|has not changed)/
```

Someone could test dependency for package ewget, if anything other is using it.

**Comment by ericpaulbishop** [comment]
It could, but this is not an improvement.

In order to login to the freedns.afraid.org site you need a username and a password. So you *need to know your username and password.* Then, on top of that, there is the key which can be retrieved using your username and password. The current configuration retrieves the key automatically.

Making people retrieve the key themselves is inferior to the current configuration, given that one way or another they need to know the username/password.
