### ISSUE TITLE
Added menu not work in latest commit

### ISSUE THREAD

**Issue by cpexplorer** [ericpaulbishop/gargoyle#637]
I add menu “luci” to redirect to luci in my router，it works well in former commits，but in latest commit，it makes no response or in other words，it can not redirect after i click the luci menu(luci support has been added in my firmware)
`config display 'display'
           option luci 'luci'
config scripts 'scripts'
           option luci 'cgi-bin/luci'`
![2017-06-25_102858](https://user-images.githubusercontent.com/19789201/27513268-7d16812a-5992-11e7-8495-f03debf4605d.png)

**Comment by lantis1008** [comment]
What if you make a submenu under the "luci" menu which also takes you to luci.
I assume this will then work?

**Comment by cpexplorer** [comment]
@lantis1008 But the menu works fine in former commits，what may cause it fail in the latest?

**Comment by lantis1008** [comment]
The menu system (and the code which forms it) have changed. I didn't write that bit, so i'm just trying to understand where the problem is.
I expect that the URL you are setting for it is being overwritten, if you examine it with the dev console for your browser.

**Comment by lantis1008** [comment]
The reason i asked you that question, is because of the following line
https://github.com/ericpaulbishop/gargoyle/blob/master/package/gargoyle/files/www/js/common.js#L2918
Which is more than likely causing you the problem. If you add a submenu, it should work.

If that does make it work, then a rewrite surrounding that line should take place, because while it works for the default system, it should probably support external modification reasonably readily.

**Comment by cpexplorer** [comment]
It really woks as you say:
`config display 'display'
	option luci 'luci'
	option luci_redirect 'redirect'

config scripts 'scripts'
	option luci_redirect 'cgi-bin/luci'

config 600 'luci'
	option redirect '100'
`

**Comment by lantis1008** [comment]
Thanks, i'l ltry and think about how to solve this.
@ericpaulbishop

**Comment by cpexplorer** [comment]
You are welcome, and please make me noticed if this issue fixed, many thanks!

**Comment by cpexplorer** [comment]
Any progress yet?
