### ISSUE TITLE
Update Dnsmasq,  to 2.78

### ISSUE THREAD

**Issue by tapper82** [ericpaulbishop/gargoyle#661]
We really should update if we can.

Google security engineers have spotted not one, not two, but seven serious flaws in Dnsmasq.
https://www.theregister.co.uk/2017/10/02/dnsmasq_flaws/
https://security.googleblog.com/2017/10/behind-masq-yet-more-dns-and-dhcp.html

**Comment by obsy** [comment]
CC has been updated: https://github.com/openwrt/openwrt/commit/c69ccdd30724615d115c4e0a38d3be98f93f08f2

**Comment by lantis1008** [comment]
I’ll do a PR tonight. 
We should probably do a 1.9.3.

**Comment by lantis1008** [comment]
Alas, i am not smart enough to solve the IMQ conflicts that occurred in this kernel update.
@ericpaulbishop ?


Lots of security fixes for Chaos Calmer branch (suggest we maybe need to 1.9.3 this?) 
- Update Kernel from 3.18.45 to 3.18.71
- Patch 029 no longer required (slightly different version included in tree)
- Dropbear, dnsmasq. samba updated (CVE fixes)
- **IMPORTANT:** **TELNET disabled in favour of passwordless SSH**. [We could revert this behaviour](http://git.openwrt.org/?p=15.05/openwrt.git;a=commit;h=bff2da1713ba42f29a700f496b533b2d766c77b5) if you prefer? Otherwise this needs to be communicated to userbase (this is probably best done through forum as the need arises). This applies to after reset, sysupgrade without preserve and failsafe.

**Comment by ericpaulbishop** [comment]
I agree we need to do another release with the latest dnsmasq given the severity of the issues. Should probably be 1.10.0, not 1.9.3.  I'll handle the IMQ issue.

The telnet/ssh isn't an issue at all -- we never use telnet. Instead we always initialize ssh with a default password "password" so there is never a case where the device is not password protected.

**Comment by obsy** [comment]
@lantis1008: we use separate package for samba, so it require upgrade too.

**Comment by lantis1008** [comment]
Won’t this disable default telnet behaviour during Failsafe?
Not that this is a big problem, just a change to be communicated.
Thanks @ericpaulbishop 

Yes true I forgot that @obsy

**Comment by ericpaulbishop** [comment]
You're right, ssh in failsafe is a change, but that should be fine. It's not a huge change like it would be if we were using the default telnet at boot.

**Comment by ericpaulbishop** [comment]
It should now be building with the latest CC code, with dnsmasq 2.78. Still haven't updated samba though.

**Comment by fengchen-github** [comment]
I recommend compiling ext4 formatted images for x86 platforms and uploading .config configuration files.@ericpaulbishop @lantis1008
