### ISSUE TITLE
The setting of using another mac address is not remembered.

### ISSUE THREAD

**Issue by WildRat** [ericpaulbishop/gargoyle#711]
![image](https://user-images.githubusercontent.com/1486048/34464055-4934e582-ee79-11e7-9758-48daa1b4a25d.png)
After I apply the settings, or when I open this settings page, the checkbox "use custom mac address" is always inactive. And if I apply the settings without re-setting it, the external mac address will return to the factory value.

**Comment by lantis1008** [comment]
The following is expected behaviour:
- If you set a custom mac address EQUAL TO the default mac address, the box will untick itself

Is this what you are experiencing?

If not, please provide additional details.
Everything i tested worked fine.

**Comment by lantis1008** [comment]
Any update?

**Comment by WildRat** [comment]
It seems that the problem is different: when you set different mac-address all works as you wrote - the box remains checked, but after this, when you try to return to default and remove this checkbox, then the address does not return to the default value, while the checkbox remains unchecked. This is a bit confusing. If you check the box and use the factory mac-address value, then the check mark will be deactivated on a next page reload- everything works as you described.

**Comment by lantis1008** [comment]
Confirmed the issue. Just to summarise:
1. Starting with Default MAC (say 11:22:33:44:55:66), we select to use a custom MAC (say AA:BB:CC:DD:EE:FF)
2. After saving settings, custom MAC is in effect, and checkbox shows we are using a custom MAC
3. If we now want to revert to Default MAC, we uncheck the box and hit save
4. The box is unchecked and the interface says we are using Default MAC, but we are actually still using Custom MAC


I have added an additional condition to the "Use Custom Mac" check function.
If the box is unchecked, but the Current MAC is different to the Default MAC, then it will set a Custom MAC equal to the Default MAC. This will cause the back end network config to properly change the MAC address back to default for us.
The interface will show as no custom MAC in use, however the back end config will show that a custom MAC is in use (albeit, the default one).
If the user hits save at some point in the future, the back end custom MAC will then disappear as it is no longer required. If they never hit save again, there is no harm caused by this being present.

You can test this yourself by changing the following line in basic.js from:
```javascript
var ifCustomMac = function(value){ return (document.getElementById('wan_use_mac').checked == true); };
```
to
```javascript
var ifCustomMac = function(value){ return (document.getElementById('wan_use_mac').checked == true) || (defaultWanMac != currentWanMac); };
```
