### ISSUE TITLE
When internet source is not Wan plugins page show warning.

### ISSUE THREAD

**Issue by WildRat** [ericpaulbishop/gargoyle#720]
When internet source is not Wan plugins page show warning. And its poorly aligned too.
![temp](https://user-images.githubusercontent.com/1486048/34961098-7adb80cc-fa46-11e7-8c88-19d55c37faa6.png)

**Comment by d3fz** [comment]
I've already fixed this locally a while ago, among other countless formatting fixes to the UI.

I'm gradually pushing the updates, so it doesn't become one giant PR with fixes for everything at the same.

>When internet source is not Wan plugins page show warning

I believe this is the expected behavior when there's no internet connection, as stated on the warning message.

**Comment by WildRat** [comment]
There IS internet connection, but thru WiFi - bridge, repeater, AP modes e.t.c.

**Comment by d3fz** [comment]
Now that you've mentioned, I think I've seen this message as well when setting up a wireless bridge. I'd need to test it again to be sure.

So despite the message showing up, you're able to refresh the list and install plugins normally?

**Comment by WildRat** [comment]
Yes. The check for this message is set IP on Wan port.
