### ISSUE TITLE
QoS Active Congestion Control (ACC) - getting stuck when link limit is less then 4000 kbps

### ISSUE THREAD

**Issue by Patryk122PL** [ericpaulbishop/gargoyle#742]
Hello,
So either I'm missing something or this bug appears only on my hardware (tp-link wdr4300) but it's so obvious and easy "to catch" that I'm surprised it wasn't fixed already.

If ACC lowers the link limit below 4000kbps  and link load will drop below pinger turn off threshold then the ACC will self-lock and by that I mean it won't raise link limit ever again (until router reboot of course).

I've looked up the source of QoS (qosmon.c) and found out that the point when ACC will start pinging target is at least 4000kbps link load so if ACC sets this limit below this value it can't recover.

Solution proposition: set pinger turn on treshold to 10% of max download bandwith that is configured by the user. This have to be less then 15% because ACC can set link speed between 15 and 100%

Edit: I should also mention that this code is supposed to prevent such situation but it's not doing very good job. 
`case QMON_IDLE:`
` pingon=0;`
  `//This limit should be the same as the dynamic range or we could get stuck`
 ` //in the IDLE state. `
 ` if (dbw_fil < 0.15 * DBW_UL) break;`

I have a 20 Mbps down link (LTE) and sometimes acc limits this to 3 Mbps (which is 15%). It's supposed to start pinging at 3000 kbps (on my config) but for some reason this logic won't ping target until link load reaches 4000 kbps.. Why?

**Comment by lantis1008** [comment]
I don’t think this is right. 
My understanding is that it begins pinging when 2 or more classes are considered active. 
A class is considered active at 4kbps (not 4000). Therefore your link only needs 8kbps limit for the pinger to come on and adjust (in theory).

**Comment by lantis1008** [comment]
Sorry, you’re correct about the ping logic. Ignore my last comment there. 

If the limit is set to 3000bps, if you hit 3000bps then the pinger will activate and the limit will increase (if appropriate). 
Are you observing otherwise? Is your link never hitting 3000?

I agree for safety that perhaps it should be set slightly lower, but you are the first to report this behaviour that I’ve seen. 

@pbix thoughts here?

**Comment by Patryk122PL** [comment]
This is why I'm so confused about this, because it should start to ping at 15% of max bandwith so in my case 3000 kbps, but even though link load reaches slightly above link limit, say for example 3200 kbps the ACC shows IDLE state and won't recover.

I'll take screenshots the next time my internet slows down and the acc get stuck. Should have results tomorrow.

**Comment by lantis1008** [comment]
Thanks that would be helpful. I have subscribed to the issue

**Comment by Patryk122PL** [comment]
I can't reproduce this self-lock just yet but I'm giving my connection pretty stable load using torrent and it seems to work as intended.. so if link load reaches 15% of max bandwith then acc starts to ping target. However this load doesn't reflect normal usage and I think because link load is an avg value this causes acc to get stuck in normal situations.

So either `if (dbw_fil < 0.15 * DBW_UL) break;` should be much lower value or this `dbw_fil` variable should be calculated in a shorter time frame. Also `if (dbw_fil < 0.1 * DBW_UL) qstate=QMON_IDLE;` seems a little bit too early in my opinion. 

I'd like to suggest faster link limit increasing, because with my unstable over-the-air (LTE) connection I'm observing link speed decresing by about 100-500 kbps per second when ping is high and only a couple 1-20 kbps increase per second so more ofen then not my speed limit is very close to 15% max bandwith and to restore full speed (when my ISP's cell tower isn't overloaded) I need to keep file download for 20 or more minutes. 

Also I don't understand why manual link limit is calculated as an offset to measured ping response time? For example: target ping avg is 20 so acc will set limit to 40, but if you specify this limit to 30 it doesn't set it to 30.. it sets this to calculated value (40) + user value (30). This should be fixed user's value in my opinion.

Overall I'll keep testing..

**Comment by lantis1008** [comment]
What version are you running?
Relatively recently an update was made which increased the recovery rate of the connection. 
This may fix that complaint. 

The program first calculates the absolute minimum ping that a user is entitled to on an (unsaturated) Link. This can then be adjusted upwards as required by the GUI. 
On my connection I found that the default setting gave an entitlement of 13ms, which was great, but throttled too quick causing my connection to never get over 25mbps. By adding 20ms my connection can now go full speed (minus any congestion that ACC handles very well) and ping times are always sub 40ms. 

I don’t think it wise to allow people to enter their own value free range. Everyone will just put 1ms and then complain it doesn’t work.

**Comment by Patryk122PL** [comment]
I'm running 1.10.0 and as I said earlier my connection is very unstable so I can't use custom ping limit because of the way it's implemented. Sometimes acc will calculate ping limit as low as 25 ms and other times more than 80 ms. In my case when cell tower isn't overloaded I'm getting an avg of 30 so I would set ping limit to 45 and be done with it. However if I let ACC to decide then this comes down to at which time of a day I reboot my router. Sometimes ACC will work too slow and other times too aggresive..

Maybe there should be a description next to an input field where user specifies ping limit or it could display info like 

> User Ping Limit: 40 ms
> Suggested Limit: 35 ms

or something like that.

I would assume people that are willing to change their router's firmware have at least some basic knowledge about that kind of stuff.

Btw. I would modify the code myself and custom build it (which I did before I decided to post an issue here on github) but for whatever reason my build tends to be unstable even though it compiles ok.

**Comment by lantis1008** [comment]
The latest snapshot builds are available on the forum or my website. 

I understand your predicament, but it may require custom implementation. I’d rather wait for Paul to chime in as he wrote the module.

**Comment by Patryk122PL** [comment]
I should've mentioned that my version comes from Cezary Jackiewicz and it seems to be build from newer source than official 1.10.0. Qosmon is in version 2.3

**Comment by lantis1008** [comment]
Does @cezary have any suggestions? His users deal with mobile more often from what I’ve seen

**Comment by pbix** [comment]
lantis1008 wrote:
"I don’t think it wise to allow people to enter their own value free range. Everyone will just put 1ms and then complain it doesn’t work."

I agree completely, this is the reason and possibly the heart of all the confusion in this thread.  If the user is getting variable ping entitlements from 30- 80ms he needs a final answer always over 80ms.  Use 60ms as your user entered value to get proper values of between 90-140ms as your ping time limit.  This is the best you can hope for on such a link.  This is a case study in trying to be too aggressive with the ping limit.  Having too low of a ping limit will directly cause a lockup scenario as qosmon tries to achieve what is impossible on your link.  You must work with the worst case, not the best case if you want stable performance. 


Patryk122PL
I will tell you that you would benefit from the enhancements in v2.3.  If you will use this version and follow my advice above I think you will get the best result that can be achieved.  v2.3 is the current version in the repo and will be in the next release.  But it is backwards compatible so you can build this one executable and copy it into a v1.10 router without issue.  Or you can use one of the bleeding edge builds that Cezary provides.

I monitor the Gargoyle forum and request that if you want to discuss this issue further please start a thread there so that it can benefit other users.  I will respond in the future there.

pbix
