### ISSUE TITLE
Can add a pptpd service plug-in?

### ISSUE THREAD

**Issue by livepu** [ericpaulbishop/gargoyle#828]
This is a good routing firmware, but VPN only has openvpn. It's not very convenient to use under win. If you have a pptpd service plug-in, it's very useful.

**Comment by lantis1008** [comment]
The latest advice appears to be to avoid pptp as an old, less secure protocol for tunneling.
Openvpn is easily available under Windows and Gargoyle already has a fully functioning openvpn plugin. 

I don't think it is worth spending the time on it for these reasons. 

Please also keep feature requests to the forums rather than the issues page as per the guidelines in the future.
