### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by dengxinggao** [ericpaulbishop/gargoyle#829]
/net/ipv4/netfilter/*weburl*.ko' is missing.

wdnr4300

**Comment by dengxinggao** [comment]
ERROR: module '/home/dxg/ggluyou/gargoyle/custom-src/build_dir/target-mips_24kc_musl/linux-ar71xx/linux-4.9.184/net/ipv4/netfilter/*weburl*.ko' is missing.
modules/netfilter.mk:1106: recipe for target '/home/dxg/ggluyou/gargoyle/custom-src/bin/targets/ar71xx/generic/packages/kmod-ipt-weburl_4.9.184-1-bd4df59bf20e0ecbb0bb18cacc430cf2_mips_24kc.ipk' failed
make[4]: *** [/home/dxg/ggluyou/gargoyle/custom-src/bin/targets/ar71xx/generic/packages/kmod-ipt-weburl_4.9.184-1-bd4df59bf20e0ecbb0bb18cacc430cf2_mips_24kc.ipk] Error 1
make[4]: Leaving directory '/home/dxg/ggluyou/gargoyle/custom-src/package/kernel/linux'
time: package/kernel/linux/compile#6.26#0.97#6.22
package/Makefile:107: recipe for target 'package/kernel/linux/compile' failed
make[3]: *** [package/kernel/linux/compile] Error 2
make[3]: Leaving directory '/home/dxg/ggluyou/gargoyle/custom-src'
package/Makefile:103: recipe for target '/home/dxg/ggluyou/gargoyle/custom-src/staging_dir/target-mips_24kc_musl/stamp/.package_compile' failed
make[2]: *** [/home/dxg/ggluyou/gargoyle/custom-src/staging_dir/target-mips_24kc_musl/stamp/.package_compile] Error 2
make[2]: Leaving directory '/home/dxg/ggluyou/gargoyle/custom-src'
/home/dxg/ggluyou/gargoyle/custom-src/include/toplevel.mk:216: recipe for target 'world' failed
make[1]: *** [world] Error 2
make[1]: 离开目录“/home/dxg/ggluyou/gargoyle/custom-src”

**Comment by lantis1008** [comment]
Please share your .config file. 
Likely this is an error on your end. 

There's also good instructions for custom src building here https://www.gargoyle-router.com/wiki/doku.php?id=developer_documentation
And i would suggest following them carefully first to see if it resolves your issue.

**Comment by dengxinggao** [comment]
thank you!
I want build a fireware with MIPS FPU Emulator.
I used  `make FULL_BUILD=true custom`.
only set 
`Subtarget (Generic devices with NAND flash)`
`Target Profile (NETGEAR WNDR4300v1)  `
> Global build settings > Kernel build options
enable `[*] Compile the kernel with MIPS FPU Emulator`
and then saved.

I used  `make usb_large_nand FULL_BUILD=true`. have same error.

**Comment by lantis1008** [comment]
As the documentation i linked suggests, there is a bit of a problem with how `make custom` works. 
You will have _much_ better results if you follow the instructions i.e.
1. `make custom` and select the desired customisations (make sure you include the gargoyle specific components!)
2. Stop compilation and rescue the `.config` file from the `custom-src` folder and create a new temporary target
3. Start fresh compile under the new target

That being said, because you are just trying to make a minor change to an existing target (ar71xx.usb_large_nand), i would start with that target and make the 1 line change required, then create that as a new target and build from there.
My advice, avoid `make custom` as much as possible as it doesn't work properly (it needs fixing).

For your convenience, i've edited the config for you and shared it here:
https://pastebin.com/7uHKGbpc
I haven't test compiled this yet, but i'm reasonably confident it will work.

**Comment by dengxinggao** [comment]
It's the same error. I gave up.thank you.
