### ISSUE TITLE
suggested to increase the network access limit for management platform access

### ISSUE THREAD

**Issue by livepu** [ericpaulbishop/gargoyle#861]
Can the system enhance management access? For example, restrict unique access to LAN or WiFi 5 or WiFi 2.4

**Comment by lantis1008** [comment]
Probably, but why?

**Comment by livepu** [comment]
Too many people are linked to the route, for fear that the security of the route setting is not enough

**Comment by lantis1008** [comment]
This should be managed at your device level using either guest network, restrictions, or some custom firewall component.
These are already available in the firmware. You might request assistance on the forums for how to configure this. 

If this does not meet your needs, that would make this a feature suggestion. For feature suggestions I also prefer they are posted to the forum instead of a GitHub issue. 
See https://github.com/ericpaulbishop/gargoyle/blob/master/CONTRIBUTING.md

Hope that helps

**Comment by lantis1008** [comment]
Is there anything else required here, or can we close the issue @livepu

**Comment by livepu** [comment]
When I use guest network, I can still access route management. I think it might be safer to manage the access, restrict private LAN or private WiFi.

**Comment by lantis1008** [comment]
Please close this issue @livepu
