### ISSUE TITLE
ddns get ip error

### ISSUE THREAD

**Issue by dengxinggao** [ericpaulbishop/gargoyle#911]
Tue Jan 19 08:16:39 2021 daemon.info ddns_gargoyle[1506]: 		Successfully retrieved local ip from url: http://checkip.org
Tue Jan 19 08:16:39 2021 daemon.info ddns_gargoyle[1506]: 	local IP  = 222.211.1.x
Tue Jan 19 08:16:39 2021 daemon.info ddns_gargoyle[1506]: 	remote IP = 222.211.1.x
Tue Jan 19 08:16:39 2021 daemon.info ddns_gargoyle[1506]: 	Update not needed, IPs match
Tue Jan 19 08:31:36 2021 daemon.info ddns_gargoyle[1506]: Checking whether update needed:
Tue Jan 19 08:31:36 2021 daemon.info ddns_gargoyle[1506]: 	service provider=cloudns.net
Tue Jan 19 08:31:38 2021 daemon.info ddns_gargoyle[1506]: 		Successfully retrieved local ip from url: https://aruljohn.com
Tue Jan 19 08:31:38 2021 daemon.info ddns_gargoyle[1506]: 	local IP  = 10.20.10.22
Tue Jan 19 08:31:38 2021 daemon.info ddns_gargoyle[1506]: 	remote IP = 222.211.1.x
Tue Jan 19 08:31:39 2021 daemon.info ddns_gargoyle[1506]: 	Update successful
Tue Jan 19 08:46:36 2021 daemon.info ddns_gargoyle[1506]: Checking whether update needed:
Tue Jan 19 08:46:36 2021 daemon.info ddns_gargoyle[1506]: 	service provider=cloudns.net
Tue Jan 19 08:46:37 2021 daemon.info ddns_gargoyle[1506]: 		Successfully retrieved local ip from url: http://www.lawrencegoetz.com/programs/ipinfo/
Tue Jan 19 08:46:37 2021 daemon.info ddns_gargoyle[1506]: 	local IP  = 222.211.1.x
Tue Jan 19 08:46:37 2021 daemon.info ddns_gargoyle[1506]: 	remote IP = 10.20.10.22
Tue Jan 19 08:46:37 2021 daemon.info ddns_gargoyle[1506]: 	Update successful
Tue Jan 19 09:01:36 2021 daemon.info ddns_gargoyle[1506]: Checking whether update needed:
Tue Jan 19 09:01:36 2021 daemon.info ddns_gargoyle[1506]: 	service provider=cloudns.net
Tue Jan 19 09:01:37 2021 daemon.info ddns_gargoyle[1506]: 		Successfully retrieved local ip from url: http://myipinfo.net
Tue Jan 19 09:01:37 2021 daemon.info ddns_gargoyle[1506]: 	local IP  = 222.211.1.x
Tue Jan 19 09:01:37 2021 daemon.info ddns_gargoyle[1506]: 	remote IP = 222.211.1.x
Tue Jan 19 09:01:37 2021 daemon.info ddns_gargoyle[1506]: 	Update not needed, IPs match

aruljohn.com Often identified as an intranet IP address，but my ip not changed。

**Comment by dengxinggao** [comment]
Gargoyle 1.12.0
Phicomm PSG1218 rev.A

**Comment by lantis1008** [comment]
Hi @dengxinggao ,

This has already been fixed in 1.13.x (https://github.com/ericpaulbishop/gargoyle/commit/063dfd1b40b088ab7ac3a1f87e55056c544fb75c), and also backported to 1.12.x (https://github.com/ericpaulbishop/gargoyle/commit/97bc33cc7abaf52bf450b93f553c49fccd13703f).
If you build or run a more recent version than 1.12.0, you will get this fix.

If you do not want to run a more recent version, there is a temporary workaround in this forum post:
https://www.gargoyle-router.com/phpbb/viewtopic.php?p=53270#p53270
You would need to change "checkmyip" for "aruljohn" in the example.

If this solves your problem, please consider closing the issue.

**Comment by dengxinggao** [comment]
3Q
