### ISSUE TITLE
Enable kmod-usb-net-ipheth

### ISSUE THREAD

**Issue by jan-kiszka** [ericpaulbishop/gargoyle#940]
Does anything speak against enabling this driver in the configs? To my understanding, it should allow using iPhones as uplinks in wired (USB) mode, e.g and case you normal uplink is broken. I'm testing this right now (while my normal uplink is broken), and I could provide a PR then.

**Comment by lantis1008** [comment]
I'd be happy to look at a PR for this functionality. 
I'd be interested to see whether it is distinguishable as a tethered phone or it just identifies as another "usb modem".

**Comment by jan-kiszka** [comment]
Besides a kernel patch that I already integrated, this also requires usbmuxd and libimobiledevice from the openwrt packages repo. And here my knowledge ends.

**Comment by jan-kiszka** [comment]
See also https://openwrt.org/docs/guide-user/network/wan/smartphone.usb.tethering.

**Comment by lantis1008** [comment]
You can install those packages and try to make it work, and if it works suggest a PR.

All of that said, the size of the packages + kmod are almost 1.5MB, which makes it **very** difficult to include in the default images. It could be wrapped into a plug-in maybe, or the packages would need to be stripped down.

If you're not able to make a PR for this, can I please suggest this issue is closed?
I'm happy to assist to some degree (packing it into a plug-in for example) but I'm not (at this point in time) willing to implement the whole thing myself.

**Comment by jan-kiszka** [comment]
I've copied over all recipes from the package repo and I'm build that now (single core due to broken parallel build...). Let's see if I get it working at all, then decide.

I agree that the size will be a problem (libxml2...). That looked differently when I only starred at the kmod (10K).

**Comment by jan-kiszka** [comment]
Ok, making progress: All packages are in, the phone suddenly asks if it should trust the router, and then I get a new interface: eth2 on my wrt32x.

That interface is not directly configurable as WAN. I've hacked `/etc/gargoyle_default_ifs` on the device to make that work, but we will need a real UI extension for that.

**Comment by lantis1008** [comment]
Please close
